version: "3"

services:
  techtalks.producer:
    image: nilehgule/techtalksproducer:azurecontainerapp
    build:
      context: src
      dockerfile: Dockerfile-TechTalksMQProducer

  techtalks.consumer:
    image: nileshgule/techtalksconsumer:azurecontainerapp
    build:
      context: src
      dockerfile: Dockerfile-TechTalksConsumer
